FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app
COPY AspNetCoreDemo.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app/publish --no-restore

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
CMD ["dotnet", "/app/publish/AspNetCoreDemo.dll"]
