FROM maven:3.9-eclipse-temurin-17

WORKDIR /app
COPY pom.xml .
RUN mvn -q -e -DskipTests dependency:go-offline

COPY src ./src
RUN mvn -q -DskipTests package

EXPOSE 8080
CMD ["java","-jar","/app/target/demo-0.0.1-SNAPSHOT.jar"]
